config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users, only: [:new, :create]
  get "/auth/twitter", as: :sign_in_with_twitter
  get "auth/twitter/callback" => "callbacks#twitter"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get "/about"  => "home#about"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show] do
        resources :answers, only: [:create]
      end
    end
  end

  resources :questions do
    resources :votes, only: [:create, :update, :destroy]

    get :search, on: :collection

    post :flag, on: :member

    post :mark_done

    resources :answers, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

  end

  resources :likes, only: [:index]

  get "/greet/:name" => "home#greet", as: :greet

  get  "/cowsay" => "cowsay#index"
  post "/cowsay" => "cowsay#create", as: :cowsay_submit

  get "/temperature_convertor" => "temperature_convertor#index"
  post "/temperature_convertor" => "temperature_convertor#convert", as: :convert_submit
  root "home#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :tweet_it

  # 'has_many' helps us set up the association between question model and the
  # answer model. In this case 'has_many' assumes that the answers table constraint
  # a field named 'question_id' that is an integer(this is a Rails convention)
  # the dependent option takes values like 'destroy' and 'nullify'
  # 'destroy' will make Rails automatically delete associated answers before deleting the question.
  # 'nullify' will make Rails turn 'question_id' values of associated records
  # to 'NULL' before deleting the question.
  has_many :answers, dependent: :destroy
  belongs_to :category
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates(:title, {presence: true, uniqueness: true})

  # by having the option: uniqueness: {scope: :title} it ensures that the body
  # must be unique in combination with the title.
  validates :body, presence:   true,
                   length:     {minimum: 7},
                   uniqueness: {scope: :title}

  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  # VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # validates :email, format: VALID_EMAIL_REGEX

  validate :no_monkey
  validate :no_title_in_body

  after_initialize :set_defaults
  before_validation :cap_title, :squeeze_space
  # before_save      :cap_title
  # before_save      :squeeze_space

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders, :history]

  mount_uploader :image, ImageUploader

  # scope :search, lambda {|word| where("title ILIKE ? OR body ILIKE ?", "%#{word}%", "%#{word}%")}
  def self.search(word)
    where("title ILIKE ? OR body ILIKE ?", "%#{word}%", "%#{word}%")
  end

  # scope :recent, lambda {|count| where("created_at > ?", 3.days.ago).limit(count)}
  # def self.recent(count)
  #   where("created_at >?", 3.days.ago).limit(count)
  # end

  def new_first_answers
    answers.order(created_at: :desc)
  end

  def liked_by?(user)

    likes.exists?(user: user)
    # we already have access to question because we're in the question controller
  end

  def like_for(user)
    # likes.where(question: @question, user: current_user).first
    likes.find_by_user_id user
  end

  def voted_by?(user)
    votes.exists?(user: user)
  end

  def vote_for(user)
    votes.find_by_user_id user
  end

  def voted_up_by?(user)
    voted_by?(user) && vote_for(user).is_up?
  end

  def voted_down_by?(user)
    voted_by?(user) && !vote_for(user).is_up?
  end

  def up_votes
    votes.where(is_up: true).count
  end

  def down_votes
    votes.where(is_up: false).count
  end

  def vote_sum
    up_votes - down_votes
  end

  # def to_param
  #   "#{id}-#{title}".parameterize
  # end

  # delegate :name, to: :category, prefix: true
  def category_name
    category.name
  end

  delegate :first_name, :last_name, to: :user, prefix: true

  private

  def squeeze_space
    self.title.squeeze!(" ") if title
    self.body.squeeze!(" ") if body
  end

  def cap_title
    self.title = title.capitalize if title
  end

  def set_defaults
    self.view_count ||= 0
  end

  def no_monkey
    if title && title.include?("monkey")
      errors.add(:title, "No monkey please!")
    end
  end

  def no_title_in_body
    if body.include?(title)
      errors.add(:body, "The title is in the body!")
    end
  end

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::BaseController
  DEFAULT_PER_PAGE = 7
  skip_before_action :authenticate_api_user

  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).per(DEFAULT_PER_PAGE)
  end

  def show
    question = Question.find params[:id]
    question_json = ActiveModelSerializers::SerializableResource.new(question)
    render json: {question: question_json}
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_owner, only: [:edit, :destroy, :update]

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    @question.user = current_user
    if @question.save
      if @question.tweet_it
        client = Twitter::REST::Client.new do |config|
          config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
          config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
          config.access_token        = current_user.twitter_token
          config.access_token_secret = current_user.twitter_secret
        end
        client.update "#{@question.body}"
      end
      flash[:notice] = "Question created!"
      redirect_to question_path(@question), notice: "Question created!"
    else
      flash[:alert] = "Question not created!"
      render :new
    end
  end

  def show
    @question.increment!(:view_count)
    @answer = Answer.new
    respond_to do |format|
      format.html
      format.json { render json: {question: @question, answers: @question.answers} }
    end
  end

  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).per(7)
    respond_to do |format|
      format.html
      format.json { render json: @questions }
    end
  end

  def edit
  end

  def update
    @question.slug = nil
    if @question.update question_params
      redirect_to question_path(@question), notice: "Question updated"
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: "Question deleted"
  end

  private

  def question_params
    # In the line below we're using the 'strong parameters' feature of Rails
    # In the line we're "requiring" that the "params" hash has a key
    # called question and we're only allowing the 'title' and the 'body' to be fetched.
    params.require(:question).permit(:title, :tweet_it, :body, :category_id, :image, {tag_ids: []})
  end

  def find_question
    @question = Question.find(params[:id]).decorate
  end

  def authorize_owner
    redirect_to root_path, alert: "Access Denied" unless can? :manage, @question
  end

  def current_user_vote
    @question.vote_for(current_user)
  end
  helper_method :current_user_vote
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%# form_for is a Rails helper that expects to be given an ActiveRecord object
    as a first argument. If the object is not persisted it will automatically
    set the action for the form the associated controller create action.
    In this case it will make the action go to `questions_path` and it will
    automatically set the method to "POST"

    if @question has any of it's attributes set, it will populate the corresponding field with that data.

    %>
<%# if @question is persisted then the `form_for` helper will make the action submit to question_path(@question) and it will make the HTTP request PATCH.
form_for will also prepopulate the fields with the data fetched from the database%>
<%#= @question.errors.full_messages.join(", ") %>
<%= simple_form_for @question do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :image %>
  <%= f.association :tags, as: :check_boxes %>
  <%= f.association :category %>
  <% if current_user.using_twitter? && !@question.persisted? %>
    <%= f.input :tweet_it, as: :boolean %>
  <% end %>
  <!-- REPLACED BY SIMPLE FORM -->
  <!-- <div> -->
    <%#= f.label :title %>
    <%#= f.text_field :title %>
  <!-- </div> -->
  <!-- <div> -->
    <%#= f.label :body %>
    <%#= f.text_area :body %>
  <!-- </div> -->
  <!-- <div> -->
    <%#= f.label :tag_ids %>
    <%#= f.collection_check_boxes(:tag_ids, Tag.order(:title), :id, :title) %>
  <!-- </div> -->
  <!-- <div> -->
    <%#= f.collection_select :category_id, Category.order(:name), :id, :name %>
  <!-- </div> -->
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/questions/_vote.html.erb
<span id="votes">
  <% if question.voted_up_by?(current_user) %>
    <%= link_to "Undo Vote Up",
                question_vote_path(question, current_user_vote),
                method: :delete,
                remote: true,
                data: {disable_with: "...."} %>
    (<%= question.vote_sum %>)
    <%= link_to "Vote Down",
                question_vote_path(question, current_user_vote,
                                  {vote: {is_up: false}}),
                method: :patch,
                remote: true %>
  <% elsif question.voted_down_by?(current_user) %>
    <%= link_to "Vote Up",
                question_vote_path(question, current_user_vote,
                                  {vote: {is_up: true}}),
                method: :patch,
                remote: true %>
    (<%= question.vote_sum %>)
    <%= link_to "Undo Vote Down",
                question_vote_path(question, current_user_vote),
                method: :delete,
                remote: true,
                data: {disable_with: "...."} %>
    |
  <% else %>
    <%= link_to "Vote Up",
                question_votes_path(question, vote: {is_up: true}),
                remote: true,
                method: :post %>
    (<%= question.vote_sum %>)
    <%= link_to "Vote Down",
                question_votes_path(question, vote: {is_up: false}),
                remote: true,
                method: :post %>
  <% end %>
</span>

app/views/questions/edit.html.erb
<h1>Edit Questions</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |question| %>
  <%= link_to question.title, question_path(question) %>
  <hr>
<% end %>
<%= paginate @questions %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%# render 'form' will look for a partial named '_form.html.erb' within the same folder as this file (new.html.erb). Partials have access to the same things as this file such as instance variables and helper methods. %>
<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p>Views: <%= @question.view_count %></p>
<p>Created By: <%= @question.user_name %></p>

<div>
  <% if @question.liked_by?(current_user) %>
    <%= @question.thumbs_up_button %>
  <% else %>
    <%= @question.thumbs_down_button %>
  <% end %>
  (<%= @question.likes.count %>)
</div>

<%= render "/questions/vote", question: @question %>

<!-- <div class="edit_delete"> -->
  <% if can? :manage, @question %>
    <%= link_to "Edit", edit_question_path(@question) %> |
    <%= link_to "Delete", question_path(@question),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
  <% end %>

<div class="image">
  <%= image_tag @question.image.url(:medium) %>
</div>
<!-- </div> -->

<p>Tags: <%= @question.tags.map { |t| t.title }.join(", ") %></p>
<%#= form_for @answer, url: question_answers_path(@question) do %>
<h2>Create an Answer</h2>
<div id="answer-form">
  <%= render "answers/form" %>
</div>

<h2>Answers</h2>
<div id="answers">
  <% @question.answers.each do |ans| %>
    <%= render "/answers/answer", answer: ans %>
  <% end %>
</div>