config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users, only: [:new, :create]
  get "/auth/twitter", as: :sign_in_with_twitter
  get "auth/twitter/callback" => "callbacks#twitter"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get "/about"  => "home#about"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show] do
        resources :answers, only: [:create]
      end
    end
  end

  resources :questions do
    resources :votes, only: [:create, :update, :destroy]

    get :search, on: :collection

    post :flag, on: :member

    post :mark_done

    resources :answers, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

  end

  resources :likes, only: [:index]

  get "/greet/:name" => "home#greet", as: :greet

  get  "/cowsay" => "cowsay#index"
  post "/cowsay" => "cowsay#create", as: :cowsay_submit

  get "/temperature_convertor" => "temperature_convertor#index"
  post "/temperature_convertor" => "temperature_convertor#convert", as: :convert_submit
  root "home#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  validates :body, presence: true, uniqueness: {scope: :question_id}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @answer           = Answer.new answer_params
    @question         = Question.find params[:question_id]
    @answer.question  = @question

    respond_to do |format|

      if @answer.save
        AnswersMailer.notify_question_owner(@answer).deliver_later

        format.html { redirect_to question_path(@question), notice: "Answer created!" }
        format.js { render :create_success } # will look for file in view called answers/success_create.js

      else
        format.html { render "/questions/show" }
        format.js { render :create_failure }
      end
    end
  end

  def destroy
    question      = Question.find params[:question_id]
    @answer        = Answer.find params[:id]
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to question_path(question), notice: "Answer deleted" }
      format.js { render }
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::BaseController

  # body = the answer | params: {body: "the answer"}
  # answer[body] = the answer | params: {answer: {body:"the answer"}}

  def create
    question          = Question.find params[:question_id]
    answer            = Answer.new answer_params
    answer.question   = question
    answer.user       = @user
    answer.save
    render json: {success: true}
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def authenticate_api_user
    user = User.find_by_api_key params[:api_key]
    head :forbidden unless user
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/api/v1/answers_helper.rb
module Api::V1::AnswersHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id(answer) %>">
  <%= answer.body %>
  <% if can? :manage, answer %>
    <%= link_to "Delete", question_answer_path(@question, answer),
                          method: :delete,
                          remote: true,
                          data: {confirm: "Are you sure?"} %>
  <% end %>
  <hr>
</div>

app/views/answers/_form.html.erb
<%#= @answer.errors.full_messages.join(", ") %>
<%= simple_form_for [@question, @answer], remote: true do |f| %>
  <%= f.input :body %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/answers/create_failure.js.erb
// alert("Failed to create answer")
$('#answers-form').html("<%= j render 'form' %>");

app/views/answers/create_success.js.erb
//alert("Inside create success partial");
$('#answers').prepend("<%= j(render('/answers/answer', {answer: @answer})) %>");
<% @answer = Answer.new %>
$('#answer-form').html("<%= j render 'form' %>");

app/views/answers/destroy.js.erb
$('#<%= dom_id(@answer) %>').fadeOut(1000, function(){ $(this).remove(); });