config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  resources :users, only: [:new, :create]
  get "/auth/twitter", as: :sign_in_with_twitter
  get "auth/twitter/callback" => "callbacks#twitter"

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  get "/about"  => "home#about"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions, only: [:index, :show] do
        resources :answers, only: [:create]
      end
    end
  end

  resources :questions do
    resources :votes, only: [:create, :update, :destroy]

    get :search, on: :collection

    post :flag, on: :member

    post :mark_done

    resources :answers, only: [:create, :destroy]

    resources :likes, only: [:create, :destroy]

  end

  resources :likes, only: [:index]

  get "/greet/:name" => "home#greet", as: :greet

  get  "/cowsay" => "cowsay#index"
  post "/cowsay" => "cowsay#create", as: :cowsay_submit

  get "/temperature_convertor" => "temperature_convertor#index"
  post "/temperature_convertor" => "temperature_convertor#convert", as: :convert_submit
  root "home#index"

end

app/views/layouts/_navbar.html.erb
<%= link_to "Home", root_path %>
|
<!-- <a href="<%= about_path %>">About Us</a> -->

<!-- <a href="<%= about_url %>">About Us</a> -->

<%#= link_to("About Us", about_path, {class: "abc", id: "xyz"}) %>
<!-- Instead of using an <a href> tag, we can use ruby and do link_to -->
<%#= link_to "Cowsay", cowsay_path %>

<%= link_to "New Question", new_question_path %>
|
<%= link_to "All Questions", questions_path %>
|
<% if user_signed_in? %>
  <%= link_to "Liked Questions", likes_path %>
  |
  Hello, <%= current_user.first_name %>
  <%= link_to "Sign Out", sessions_path, method: :delete %>
<% else %>
  <%= link_to "Sign Up", new_user_path %> |
  <%= link_to "Sign In", new_session_path %> |
  <%= link_to "Sign In With Twitter", sign_in_with_twitter_path %>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "/layouts/navbar" %>

  <% if flash[:notice] %>
    <div class="flash-notice"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
    <div class="flash-alert"><%= flash[:alert] %></div>
  <% end %>

<%= yield %>
</div>

</body>
</html>